-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
///																	DOORS																      ///
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
local SmallBridge_PartAssemblyData = {

	[ "models/smallbridge/hulls,sw/sbhullcurvel.mdl"			] = { { type = "SWSH" , pos = Vector(  446.4 ,-334.8,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector( -334.8 , 446.4,  0  ) , dir = Angle(  0, 90,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhullcurvem.mdl"			] = { { type = "SWSH" , pos = Vector(  334.8 ,-223.2,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector( -223.2 , 334.8,  0  ) , dir = Angle(  0, 90,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhullcurves.mdl"			] = { { type = "SWSH" , pos = Vector(  223.2 ,-111.6,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector( -111.6 , 223.2,  0  ) , dir = Angle(  0, 90,  0) } } ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,sw/sbhulle05.mdl"				] = { { type = "SWSH" , pos = Vector(   55.8 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector(  -55.8 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhulle1.mdl"				] = { { type = "SWSH" , pos = Vector(  111.6 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector( -111.6 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhulle2.mdl"				] = { { type = "SWSH" , pos = Vector(  223.2 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector( -223.2 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhulle3.mdl"				] = { { type = "SWSH" , pos = Vector(  334.8 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector( -334.8 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhulle4.mdl"				] = { { type = "SWSH" , pos = Vector(  446.4 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector( -446.4 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } } ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,sw/sbhulledh.mdl"				] = { { type = "SWDH" , pos = Vector(  111.6 ,   0  , 65.1) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWDH" , pos = Vector( -111.6 ,   0  , 65.1) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhulledh05.mdl"				] = { { type = "SWDH" , pos = Vector(   55.8 ,   0  , 65.1) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWDH" , pos = Vector(  -55.8 ,   0  , 65.1) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhulledh2.mdl"				] = { { type = "SWDH" , pos = Vector(  223.2 ,   0  , 65.1) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWDH" , pos = Vector( -223.2 ,   0  , 65.1) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhulledh3.mdl"				] = { { type = "SWDH" , pos = Vector(  334.8 ,   0  , 65.1) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWDH" , pos = Vector( -334.8 ,   0  , 65.1) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhulledh4.mdl"				] = { { type = "SWDH" , pos = Vector(  446.4 ,   0  , 65.1) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWDH" , pos = Vector( -446.4 ,   0  , 65.1) , dir = Angle(  0,180,  0) } } ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,sw/sbhulleflip.mdl"				] = { { type = "SWSH" , pos = Vector(  111.6 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector( -111.6 ,   0  ,  0  ) , dir = Angle(  0,180,180) } } ,
	[ "models/smallbridge/hulls,sw/sbhullend.mdl"				] = { { type = "SWSH" , pos = Vector(  111.6 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhullenddh.mdl"				] = { { type = "SWDH" , pos = Vector(  111.6 ,   0  , 65.1) , dir = Angle(  0,  0,  0) } } ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,sw/sbhullr.mdl"					] = { { type = "SWSH" , pos = Vector(  111.6 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector(    0   , 111.6,  0  ) , dir = Angle(  0, 90,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhullrdh.mdl"				] = { { type = "SWDH" , pos = Vector(  111.6 ,   0  , 65.1) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWDH" , pos = Vector(    0   , 111.6, 65.1) , dir = Angle(  0, 90,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhullrtri.mdl"				] = { { type = "SWSH" , pos = Vector(  111.6 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector(    0   , 111.6,  0  ) , dir = Angle(  0, 90,  0) } } ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,sw/sbhullslanthalfl.mdl"		] = { { type = "SWSH" , pos = Vector(  111.6 ,  55.8,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector( -111.6 , -55.8,  0  ) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhullslanthalfr.mdl"		] = { { type = "SWSH" , pos = Vector(  111.6 , -55.8,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector( -111.6 ,  55.8,  0  ) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhullslantl.mdl"			] = { { type = "SWSH" , pos = Vector(  111.6 , 111.6,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector( -111.6 ,-111.6,  0  ) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhullslantr.mdl"			] = { { type = "SWSH" , pos = Vector(  111.6 ,-111.6,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "SWSH" , pos = Vector( -111.6 , 111.6,  0  ) , dir = Angle(  0,180,  0) } } ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,sw/sbhullt.mdl"					] = { { type = "SWSH" , pos = Vector(  111.6 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } ,
																	  { type = "SWSH" , pos = Vector(    0   ,-111.6,  0  ) , dir = Angle(  0,270,  0) } , 
																	  { type = "SWSH" , pos = Vector(    0   , 111.6,  0  ) , dir = Angle(  0, 90,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhulltdh.mdl"				] = { { type = "SWDH" , pos = Vector(  111.6 ,   0  , 65.1) , dir = Angle(  0,  0,  0) } ,
																	  { type = "SWDH" , pos = Vector( -111.6 ,   0  , 65.1) , dir = Angle(  0,180,  0) } , 
																	  { type = "SWDH" , pos = Vector(    0   , 111.6, 65.1) , dir = Angle(  0, 90,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhulltdl.mdl"				] = { { type = "SWSH" , pos = Vector(  111.6 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } ,
																	  { type = "SWSH" , pos = Vector(    0   ,-223.2,  0  ) , dir = Angle(  0,270,  0) } , 
																	  { type = "SWSH" , pos = Vector(    0   , 223.2,  0  ) , dir = Angle(  0, 90,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhulltdldw.mdl"				] = { { type = "DWSH" , pos = Vector(  111.6 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } ,
																	  { type = "SWSH" , pos = Vector(    0   ,-223.2,  0  ) , dir = Angle(  0,270,  0) } , 
																	  { type = "SWSH" , pos = Vector(    0   , 223.2,  0  ) , dir = Angle(  0, 90,  0) } } ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,sw/sbhulltri1.mdl"				] = { { type = "SWSH" , pos = Vector(  -74.4 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhulltri2.mdl"				] = { { type = "SWSH" , pos = Vector(  -74.4 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } ,
																	  { type = "SWSH" , pos = Vector(   37.2 ,64.432,  0  ) , dir = Angle(  0, 60,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhulltri3.mdl"				] = { { type = "SWSH" , pos = Vector(  -74.4 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } ,
																	  { type = "SWSH" , pos = Vector(   37.2 , 64.43,  0  ) , dir = Angle(  0, 60,  0) } ,
																	  { type = "SWSH" , pos = Vector(   37.2 ,-64.43,  0  ) , dir = Angle(  0,-60,  0) } } ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,sw/sbhullx.mdl"					] = { { type = "SWSH" , pos = Vector(  111.6 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } ,
																	  { type = "SWSH" , pos = Vector( -111.6 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } , 
																	  { type = "SWSH" , pos = Vector(    0   ,-111.6,  0  ) , dir = Angle(  0,270,  0) } , 
																	  { type = "SWSH" , pos = Vector(    0   , 111.6,  0  ) , dir = Angle(  0, 90,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhullxdh.mdl"				] = { { type = "SWDH" , pos = Vector(  111.6 ,   0  , 65.1) , dir = Angle(  0,  0,  0) } ,
																	  { type = "SWDH" , pos = Vector( -111.6 ,   0  , 65.1) , dir = Angle(  0,180,  0) } , 
																	  { type = "SWDH" , pos = Vector(    0   ,-111.6, 65.1) , dir = Angle(  0,270,  0) } , 
																	  { type = "SWDH" , pos = Vector(    0   , 111.6, 65.1) , dir = Angle(  0, 90,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhullxdl.mdl"				] = { { type = "SWSH" , pos = Vector(  111.6 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } ,
																	  { type = "SWSH" , pos = Vector( -111.6 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } , 
																	  { type = "SWSH" , pos = Vector(    0   ,-223.2,  0  ) , dir = Angle(  0,270,  0) } , 
																	  { type = "SWSH" , pos = Vector(    0   , 223.2,  0  ) , dir = Angle(  0, 90,  0) } } ,
	[ "models/smallbridge/hulls,sw/sbhullxdldw.mdl"				] = { { type = "SWSH" , pos = Vector(  223.2 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } ,
																	  { type = "SWSH" , pos = Vector( -223.2 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } , 
																	  { type = "DWSH" , pos = Vector(    0   ,-111.6,  0  ) , dir = Angle(  0,270,  0) } , 
																	  { type = "DWSH" , pos = Vector(    0   , 111.6,  0  ) , dir = Angle(  0, 90,  0) } } ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,dw/sbhulldwe05.mdl"				] = { { type = "DWSH" , pos = Vector(   55.8 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "DWSH" , pos = Vector(  -55.8 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,dw/sbhulldwe1.mdl"				] = { { type = "DWSH" , pos = Vector(  111.6 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "DWSH" , pos = Vector( -111.6 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,dw/sbhulldwe2.mdl"				] = { { type = "DWSH" , pos = Vector(  223.2 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "DWSH" , pos = Vector( -223.2 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,dw/sbhulldwe3.mdl"				] = { { type = "DWSH" , pos = Vector(  334.8 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "DWSH" , pos = Vector( -334.8 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } } ,
	[ "models/smallbridge/hulls,dw/sbhulldwe4.mdl"				] = { { type = "DWSH" , pos = Vector(  446.4 ,   0  ,  0  ) , dir = Angle(  0,  0,  0) } , 
																	  { type = "DWSH" , pos = Vector( -446.4 ,   0  ,  0  ) , dir = Angle(  0,180,  0) } } ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,dw/sbhulldwedh.mdl"				] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwedh05.mdl"			] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwedh2.mdl"			] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwedh3.mdl"			] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwedh4.mdl"			] = {  	} ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,dw/sbhulldweflip.mdl"			] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwend.mdl"				] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwend2.mdl"			] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwenddh.mdl"			] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwenddh2.mdl"			] = {  	} ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,dw/sbhulldwr.mdl"				] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwrdh.mdl"				] = {  	} ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,dw/sbhulldwt.mdl"				] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwtdh.mdl"				] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwtdl.mdl"				] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwtsl.mdl"				] = {  	} ,
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/hulls,dw/sbhulldwx.mdl"				] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwxdh.mdl"				] = {  	} ,
	[ "models/smallbridge/hulls,dw/sbhulldwxdl.mdl"				] = {  	} ,
----------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------
	[ "models/smallbridge/ship parts/sbcockpit1.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbcockpit2.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbcockpit2o.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbcockpit2or.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbcockpit3.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbengine1.mdl"				] = {  	} ,
	[ "models/smallbridge/ship parts/sbengine2.mdl"				] = {  	} ,
	[ "models/smallbridge/ship parts/sbengine2o.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbengine2or.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbengine3.mdl"				] = {  	} ,
	[ "models/smallbridge/ship parts/sbengine4dw.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbengine4l.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbengine4m.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbengine4r.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbengine5.mdl"				] = {  	} ,
	[ "models/smallbridge/ship parts/sbengine5dwdh.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbhulldsdwe.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbhulldsdwe2.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbhulldse.mdl"				] = {  	} ,
	[ "models/smallbridge/ship parts/sbhulldseb.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbhulldsp.mdl"				] = {  	} ,
	[ "models/smallbridge/ship parts/sbhulldsp2.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sbhulldst.mdl"				] = {  	} ,
	[ "models/smallbridge/ship parts/sblandramp.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sblandrampdw.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sblandrampdwdh.mdl"		] = {  	} ,
	[ "models/smallbridge/ship parts/sblandrampp.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sblandramppdw.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sblandramppdwdh.mdl"		] = {  	} ,
	[ "models/smallbridge/ship parts/sblanduramp.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sblandurampdw.mdl"			] = {  	} ,
	[ "models/smallbridge/ship parts/sblandurampdwdh.mdl"		] = {  	} ,

	[ "models/smallbridge/splitters/sbconvmb.mdl"				] = {  	} ,
	[ "models/smallbridge/splitters/sbconvmbdh.mdl"				] = {  	} ,
	[ "models/smallbridge/splitters/sbconvmbdw.mdl"				] = {  	} ,
	[ "models/smallbridge/splitters/sbconvmbdwdh.mdl"			] = {  	} ,
	[ "models/smallbridge/splitters/sbsplit2s-2sw.mdl"			] = {  	} ,
	[ "models/smallbridge/splitters/sbsplit2s-dw.mdl"			] = {  	} ,
	[ "models/smallbridge/splitters/sbsplitdws-dhd.mdl"			] = {  	} ,
	[ "models/smallbridge/splitters/sbsplitdws-dhm.mdl"			] = {  	} ,
	[ "models/smallbridge/splitters/sbsplitdws-dhu.mdl"			] = {  	} ,
	[ "models/smallbridge/splitters/sbsplits-dhd.mdl"			] = {  	} ,
	[ "models/smallbridge/splitters/sbsplits-dhm.mdl"			] = {  	} ,
	[ "models/smallbridge/splitters/sbsplits-dhu.mdl"			] = {  	} ,
	[ "models/smallbridge/splitters/sbsplits-dw.mdl"			] = {  	} ,
	[ "models/smallbridge/splitters/sbsplits-dwa.mdl"			] = {  	} ,
	[ "models/smallbridge/splitters/sbsplits-dwdh.mdl"			] = {  	} ,
	[ "models/smallbridge/splitters/sbsplitv.mdl"				] = {  	} ,
	[ "models/smallbridge/splitters/sbsplitvdh.mdl"				] = {  	} ,
	[ "models/smallbridge/splitters/sbsplitvw.mdl"				] = {  	} ,

	[ "models/smallbridge/height transfer/sbhtcramp.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtcramp2d.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtcramp2u.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtcrampdl.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtramp.mdl"			] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtramp05.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtrampdw.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtrampdw05.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtsdwrampd.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtsdwrampm.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtsdwrampu.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtsrampd.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtsrampm.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtsrampu.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtsrampz.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtsrampzdh.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtsrampzdw.mdl"		] = {  	} ,
	[ "models/smallbridge/height transfer/sbhtsrampzdwdh.mdl"	] = {  	} ,

	[ "models/smallbridge/panels/sbdoor.mdl"					] = { 	} ,
	[ "models/smallbridge/panels/sbdoorsquare.mdl"				] = {  	} ,
	[ "models/smallbridge/panels/sbdoorwide.mdl"				] = { 	} ,
	[ "models/smallbridge/panels/sbpaneldbsmall.mdl"			] = { 	} ,
	[ "models/smallbridge/panels/sbpaneldh.mdl"					] = { 	} ,
	[ "models/smallbridge/panels/sbpaneldhdw.mdl"				] = { 	} ,
	[ "models/smallbridge/panels/sbpaneldockin.mdl"				] = { 	} ,
	[ "models/smallbridge/panels/sbpaneldockout.mdl"			] = { 	} ,
	[ "models/smallbridge/panels/sbpaneldoor.mdl"				] = { 	} ,
	[ "models/smallbridge/panels/sbpaneldoordw.mdl"				] = { 	} ,
	[ "models/smallbridge/panels/sbpaneldoordw2.mdl"			] = { 	} ,
	[ "models/smallbridge/panels/sbpaneldooriris.mdl"			] = { 	} ,
	[ "models/smallbridge/panels/sbpaneldoorsquare.mdl"			] = { 	} ,
	[ "models/smallbridge/panels/sbpaneldoorsquaredw.mdl"		] = { 	} ,
	[ "models/smallbridge/panels/sbpaneldoorwide.mdl"			] = { 	} ,
	[ "models/smallbridge/panels/sbpaneldoorwide2.mdl"			] = { 	} ,
	[ "models/smallbridge/panels/sbpaneliris.mdl"				] = {  	} ,
	[ "models/smallbridge/panels/sbpanelsolid.mdl"				] = {  	} ,
	[ "models/smallbridge/panels/sbpanelsoliddw.mdl"			] = {  	} ,

	[ "models/smallbridge/elevators,small/sbselevb.mdl"			] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevbe.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevbedh.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevbedw.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevbr.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevbt.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevbx.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevm.mdl"			] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevme.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevmedh.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevmedw.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevmr.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevmt.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevmx.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevp0.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevp1.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevp2e.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevp2esl.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevp2r.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevp3.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevs.mdl"			] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevs2.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevslant.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevt.mdl"			] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevte.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevtedh.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevtedw.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevtr.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevtt.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,small/sbselevtx.mdl"		] = {  	} ,

	[ "models/smallbridge/elevators,large/sblelevb.mdl"			] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevbe.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevbedh.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevbr.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevbt.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevbx.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevm.mdl"			] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevme.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevmedh.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevmr.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevmt.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevmx.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevp0.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevp1.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevp2e.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevp2r.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevp3.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevs.mdl"			] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevs2.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevt.mdl"			] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevte.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevtedh.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevtr.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevtt.mdl"		] = {  	} ,
	[ "models/smallbridge/elevators,large/sblelevtx.mdl"		] = {  	} ,

	[ "models/smallbridge/hangars/sbdb1l.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb1ls.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb1m.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb1m1.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb1m12.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb1r.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb1rs.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb2l.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb2m.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb2mdw.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb2r.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb3m.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb3mdw.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb3mx.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb3mxdw.mdl"				] = {  	} ,
	[ "models/smallbridge/hangars/sbdb3side.mdl"				] = {  	} ,
	[ "models/smallbridge/hangars/sbdb4l.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb4m.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb4mdw.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdb4r.mdl"					] = {  	} ,
	[ "models/smallbridge/hangars/sbdbcomp1.mdl"				] = {  	} ,
	[ "models/smallbridge/hangars/sbdbseg1s.mdl"				] = {  	} ,
	[ "models/smallbridge/hangars/sbdbseg1ss.mdl"				] = {  	} ,
	[ "models/smallbridge/hangars/sbdbseg2s.mdl"				] = {  	} ,
	[ "models/smallbridge/hangars/sbdbseg3s.mdl"				] = {  	} ,
	[ "models/smallbridge/hangars/sbdbseg4s.mdl"				] = {  	} ,

	[ "models/smallbridge/station parts/sbbaydps.mdl"			] = {  	} ,
	[ "models/smallbridge/station parts/sbbridgecomm.mdl"		] = {  	} ,
	[ "models/smallbridge/station parts/sbbridgecommdw.mdl"		] = {  	} ,
	[ "models/smallbridge/station parts/sbbridgecommelev.mdl"	] = {  	} ,
	[ "models/smallbridge/station parts/sbbridgesphere.mdl"		] = {  	} ,
	[ "models/smallbridge/station parts/sbbridgevisor.mdl"		] = {  	} ,
	[ "models/smallbridge/station parts/sbbridgevisorb.mdl"		] = {  	} ,
	[ "models/smallbridge/station parts/sbbridgevisorm.mdl"		] = {  	} ,
	[ "models/smallbridge/station parts/sbbridgevisort.mdl"		] = {  	} ,
	[ "models/smallbridge/station parts/sbdockcs.mdl"			] = {  	} ,
	[ "models/smallbridge/station parts/sbhangarld.mdl"			] = {  	} ,
	[ "models/smallbridge/station parts/sbhangarlu.mdl"			] = {  	} ,
	[ "models/smallbridge/station parts/sbhangarlud.mdl"		] = {  	} ,
	[ "models/smallbridge/station parts/sbhangarlud2.mdl"		] = {  	} ,
	[ "models/smallbridge/station parts/sbhubl.mdl"				] = {  	} ,
	[ "models/smallbridge/station parts/sbhuble.mdl"			] = {  	} ,
	[ "models/smallbridge/station parts/sbhubls.mdl"			] = {  	} ,
	[ "models/smallbridge/station parts/sbhubs.mdl"				] = {  	} ,
	[ "models/smallbridge/station parts/sbrooml1.mdl"			] = {  	} ,
	[ "models/smallbridge/station parts/sbroomsgc.mdl"			] = {  	}

						}


for k,v in pairs( SmallBridge_PartAssemblyData ) do
	if v ~= {} then
		list.Set( "SBEP_PartAssemblyData", k , v )
	end
end