list.Set( "ButtonModels", "models/SmallBridge/Other/SBconsolelow.mdl", {} )
list.Set( "ButtonModels", "models/SmallBridge/Other/SBconsole.mdl", {} )
list.Set( "ButtonModels", "models/Slyfo/powercrystal.mdl", {} )


//SMALLBRIDGE TEXTURES
//Skin 1
list.Add( "OverrideMaterials", "spacebuild/Body" )
list.Add( "OverrideMaterials", "spacebuild/BodySkin" )
list.Add( "OverrideMaterials", "spacebuild/Hazard" )
list.Add( "OverrideMaterials", "spacebuild/Floor" )
list.Add( "OverrideMaterials", "spacebuild/SBLight" )
list.Add( "OverrideMaterials", "spacebuild/SBLight_D" )
list.Add( "OverrideMaterials", "spacebuild/Fusion" )
//Skin 2
list.Add( "OverrideMaterials", "spacebuild/Body2" )
list.Add( "OverrideMaterials", "spacebuild/Body2Skin" )
list.Add( "OverrideMaterials", "spacebuild/Hazard2" )
list.Add( "OverrideMaterials", "spacebuild/Floor2" )
list.Add( "OverrideMaterials", "spacebuild/SBLight2" )
list.Add( "OverrideMaterials", "spacebuild/SBLight2_D" )
list.Add( "OverrideMaterials", "spacebuild/Fusion2" )
//Skin 3
list.Add( "OverrideMaterials", "spacebuild/Body3" )
list.Add( "OverrideMaterials", "spacebuild/Body3Skin" )
list.Add( "OverrideMaterials", "spacebuild/Hazard3" )
list.Add( "OverrideMaterials", "spacebuild/Floor3" )
list.Add( "OverrideMaterials", "spacebuild/SBLight3" )
list.Add( "OverrideMaterials", "spacebuild/SBLight3_D" )
list.Add( "OverrideMaterials", "spacebuild/Fusion3" )
//Skin 4
list.Add( "OverrideMaterials", "spacebuild/Body4" )
list.Add( "OverrideMaterials", "spacebuild/Body4Skin" )
list.Add( "OverrideMaterials", "spacebuild/Hazard4" )
list.Add( "OverrideMaterials", "spacebuild/Floor4" )
list.Add( "OverrideMaterials", "spacebuild/SBLight4" )
list.Add( "OverrideMaterials", "spacebuild/SBLight4_D" )
list.Add( "OverrideMaterials", "spacebuild/Fusion4" )
//Skin 5
list.Add( "OverrideMaterials", "spacebuild/Body5" )
list.Add( "OverrideMaterials", "spacebuild/Body5Skin" )
list.Add( "OverrideMaterials", "spacebuild/Hazard5" )
list.Add( "OverrideMaterials", "spacebuild/Floor5" )
list.Add( "OverrideMaterials", "spacebuild/SBLight5" )
list.Add( "OverrideMaterials", "spacebuild/SBLight5_D" )
list.Add( "OverrideMaterials", "spacebuild/Fusion5" )